# Generated by Django 5.1.1 on 2024-09-23 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="costumer",
            name="user",
        ),
        migrations.AddField(
            model_name="costumer",
            name="email",
            field=models.EmailField(default="a@a.com", max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="costumer",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="costumer",
            name="name",
            field=models.CharField(default="a", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="costumer",
            name="password",
            field=models.CharField(default="a", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="costumer",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="gameowner",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_owner",
                to="shop.costumer",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review",
                to="shop.costumer",
            ),
        ),
        migrations.AlterField(
            model_name="shoppingcart",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shopping_carts",
                to="shop.costumer",
            ),
        ),
    ]
