# Generated by Django 5.1.2 on 2024-11-12 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='user_receipt',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='user_wallet',
            new_name='user',
        ),
    ]
