# Generated by Django 5.1.1 on 2024-09-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_alter_gameowner_user_alter_review_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="comment",
            field=models.CharField(default="a", max_length=255),
            preserve_default=False,
        ),
    ]
