# Generated by Django 5.1.1 on 2024-09-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_review_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameowner",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
