# Generated by Django 5.1.1 on 2024-09-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_gameowner_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="rating",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1
            ),
        ),
    ]
