# Generated by Django 5.1.2 on 2024-11-11 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_wallet_user_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_receipts', to='shop.wallet'),
        ),
    ]
